import { BaseRepository } from "./base.repository.js";
import FraudReport from "../models/FraudReport.js";

/**
 * Repository layer handling Fraud Report persistence operations
 */
export class FraudReportRepository extends BaseRepository {

  constructor() {
    super(FraudReport);
  }

  /**
   * Look up report by ID populating document and analyst metadata details
   * @param reportId Fraud Report ObjectId string
   */
  async findDetailedById(reportId: any) {
    return this.model
      .findById(reportId)
      .populate("document")
      .populate("analyst", "-password")
      .exec();
  }

  /**
   * Look up all reports generated by a specific analyst
   * @param userId Analyst User ObjectId string
   */
  async findByAnalyst(userId: any) {
    return this.model
      .find({ analyst: userId })
      .populate("document")
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Build MongoDB query filter based on filters request object
   * @param userId Analyst User ObjectId string (optional)
   * @param filters Key value filters mapping
   */
  buildFilter(userId: any, filters: Record<string, any> = {}) {
    const query: Record<string, any> = {};

    if (userId) query.analyst = userId;
    if (filters.riskLevel) query.riskLevel = filters.riskLevel;
    if (filters.decision) query.decision = filters.decision;

    if (
      filters.minRiskScore !== undefined ||
      filters.maxRiskScore !== undefined
    ) {
      query.riskScore = {};
      if (filters.minRiskScore !== undefined)
        query.riskScore.$gte = Number(filters.minRiskScore);
      if (filters.maxRiskScore !== undefined)
        query.riskScore.$lte = Number(filters.maxRiskScore);
    }

    if (filters.search) {
      query.$or = [
        { summary: { $regex: filters.search, $options: "i" } },
        { "anomalies.type": { $regex: filters.search, $options: "i" } },
        { "anomalies.description": { $regex: filters.search, $options: "i" } },
      ];
    }

    return query;
  }

  /**
   * Search, filter, and paginate reports
   * @param userId Analyst User ObjectId string (or null for all)
   * @param filters Query filter configurations
   * @param pagination Page, limit, skip parameters
   */
  async searchByAnalyst(
    userId: any,
    filters: Record<string, any> = {},
    pagination = { page: 1, limit: 10, skip: 0 },
  ) {
    return this.model
      .find(this.buildFilter(userId, filters))
      .populate("document")
      .sort({ createdAt: -1 })
      .skip(pagination.skip)
      .limit(pagination.limit)
      .exec();
  }

  /**
   * Count total reports matching filters criteria
   * @param userId Analyst User ObjectId string (or null for all)
   * @param filters Query filter configurations
   */
  async countByAnalyst(userId: any, filters: Record<string, any> = {}) {
    return this.model.countDocuments(this.buildFilter(userId, filters)).exec();
  }

}
