export const ACTION_TYPES = {
  DOCUMENT: {
    UPLOAD_START: 'DOCUMENT/UPLOAD_START',
    UPLOAD_SUCCESS: 'DOCUMENT/UPLOAD_SUCCESS',
    UPLOAD_ERROR: 'DOCUMENT/UPLOAD_ERROR',
    ANALYZE_START: 'DOCUMENT/ANALYZE_START',
    ANALYZE_SUCCESS: 'DOCUMENT/ANALYZE_SUCCESS',
  },
  AUTH: {
    LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
    LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',
    LOGOUT: 'AUTH/LOGOUT',
  },
  UI: {
    TOGGLE_THEME: 'UI/TOGGLE_THEME',
    SHOW_MODAL: 'UI/SHOW_MODAL',
    HIDE_MODAL: 'UI/HIDE_MODAL',
    SET_LOADING: 'UI/SET_LOADING',
  },
} as const;
