export const ROLES = {
  ADMIN: 'ADMIN',
  ANALYST: 'ANALYST',
  USER: 'USER',
} as const;

export type Role = keyof typeof ROLES;

export const PERMISSIONS = {
  CAN_VIEW_REPORTS: [ROLES.ADMIN, ROLES.ANALYST, ROLES.USER],
  CAN_MANAGE_USERS: [ROLES.ADMIN],
  CAN_DELETE_DOCUMENTS: [ROLES.ADMIN, ROLES.ANALYST],
  CAN_OVERRIDE_AI: [ROLES.ADMIN, ROLES.ANALYST],
} as const;
